# Generated by Django 5.1.4 on 2024-12-17 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLocation_App', '0002_alter_userlocation_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlocation',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userlocation',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='username',
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
