# Generated by Django 5.1.4 on 2024-12-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedarticle',
            name='article',
        ),
        migrations.AddField(
            model_name='savedarticle',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='savedarticle',
            name='title',
            field=models.CharField(default='No title provided', max_length=255),
        ),
        migrations.AddField(
            model_name='savedarticle',
            name='url',
            field=models.URLField(default='No URL provided'),
        ),
    ]
