# Generated by Django 5.1.4 on 2024-12-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_App', '0002_remove_savedarticle_article_savedarticle_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedarticle',
            name='description',
            field=models.TextField(blank=True, default='No description provided'),
        ),
    ]
