# Generated by Django 5.1.4 on 2024-12-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='savedarticle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newsuser',
            name='location',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='SavedArticle',
        ),
    ]
